server:
  port: 9003

#domain:
#  patient
#  - id
#    name
#    symptoms
#    diagnosis
#    treatment

nurse:
  book:
    astma: aspirin
    ADSL: mexalan
    HIV: borziacolon

accountancy:
  server:
    url: 9005