server:
  port: 9004

domain:
  patient
- id
  name
  symptoms
  diagnosis
  treatment

medicaldiagnosis:
- symptoms: gumsreduction
  diagnosis: ginvitis
  treatment: pharmacy
- symptoms: gumsbleeding
  diagnosis: paradontose
  treatment: pharmacy
- symptoms: heartache
  diagnosis: infarct
  treatment: bed
- symptoms: cough
  diagnosis: allergy
  treatment: pharmacy
- symptoms: stomagepain
  diagnosis: appendix
  treatment: bed
